# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 19:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric or contain any of the following: ". + -"', regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
